### ISSUE TITLE
Hidden cells in Global Grid are shown in visual mode

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#240]
​Although you have hidden one/some cell/s in Global Grid, they are shown (with crossed eye) in visual mode. ​

**Comment by klues** [comment]
fixed with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-02-20-12.00%2F%2B0100 - please test.

**Comment by arasaac-dga** [comment]
Great!!! Works!! Thanks

**Comment by dcg78** [comment]
Thank you so much.
It appears that I have the latest version, the problem persists. I attach two screenshots
![1676988357206blob](https://user-images.githubusercontent.com/125923692/220370071-7ee1d818-dc0e-4c35-bb5a-f22b794fec64.jpg)
![1676988337937blob](https://user-images.githubusercontent.com/125923692/220370095-cd2accda-2554-4428-949f-1fc59a108a27.jpg)

**Comment by klues** [comment]
How does the global grid look like in edit mode? Which element should be hidden? You of course could also just remove the element from the global grid instead of hiding it.

**Comment by dcg78** [comment]
Se ve así. Podría eliminarlo, pero si algun dia lo necesitara no sabria crearlo. Sobre todo el core 50, teclado, números...
![image](https://user-images.githubusercontent.com/125923692/220374416-463a860a-6a4b-4bb8-95b7-736695c6af16.png)

**Comment by dcg78** [comment]
El tamaño esta en 5 filas y 6 columnas

**Comment by klues** [comment]
OK, maybe we're talking about different things here. You've hidden the elements on the right and now you're wondering why the global grid is wider than the grid below, so this is what you don't like: 
![image](https://user-images.githubusercontent.com/2537025/220375946-865ac7bc-affd-4140-99b8-f56b2a791679.png)

Correct?

This issue was about hiding elements from the global grid, so elements in the first row, e.g. hiding the "delete"-button at the top right. So these are two different things.

I'm afraid the problem you're talking about (if I'm correct with my assumption) is intended. It's intended that hiding elements does not change the layout of the grid, so hiding the elements on the right results in the empty space on the right. So you could show these elements in the future and the user still has the other symbols on exactly the same position. This is intended because it could be confusing for the user, if the layout suddenly changes if new elements are shown.

What you could do:
Clone this grid in the menu "Manage grids" on the right in order to create a backup. Afterwards you can delete the hidden elements from the grid and you can still use the backup grid later, if you want to.

Also note that deleting an element does not delete the grids that are linked to the element. So if you would delete "Teclado", it wouldn't delete the grid with the keyboard, but only the navigation to it. So it wouldn't be too complicated to restore it in the future.

**Comment by dcg78** [comment]
Genial, tiene razón. Creo una copia de seguridad y elimino. Muchas muchas gracias!!
