### ISSUE TITLE
COMO APLICAR A ASTERIC GRID LA SOLUCION #240

### ISSUE THREAD

**Issue by dcg78** [asterics/AsTeRICS-Grid#241]
He visto que han solucionado el problema de las casillas ocultas en la solucion #240 pero no se como aplicarlo a mi comunicador. gracias

**Comment by klues** [comment]
Hello,
yes, it should be solved, if your application has already updated to the latest version.

Go to "About" and see the current version at the bottom:
![image](https://user-images.githubusercontent.com/2537025/220284557-d70b2188-3820-4d70-b932-d8644dc49aa2.png)

It should be [release-2023-02-20-12.00/+0100](https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-02-20-12.00/+0100)

If it is, it should be possible to hide elements from the global grid.
Write again, if it's not working for you.

**Comment by klues** [comment]
If it's not showing the correct/latest version, connect to the internet, open AsTeRICS Grid and wait. Normally it should update automatically within 15 minutes.

**Comment by dcg78** [comment]
Thank you so much.It appears that I have the latest version, the problem persists. I attach two screenshots




    En martes, 21 de febrero de 2023, 09:06:39 CET, Benjamin Klaus ***@***.***> escribió:  
 
 


Hello,
yes, it should be solved, if your application has already updated to the latest version.

Go to "About" and see the current version at the bottom:


It should be release-2023-02-20-12.00/+0100

If it is, it should be possible to hide elements from the global grid.
Write again, if it's not working for you.

**Comment by klues** [comment]
Sorry, I can't see the screenshots. You have to either attach it on commenting here on the github page (not replying via mail) or you can also write a mail to office@asterics-foundation.org
