### ISSUE TITLE
Sincronization doesn't cache all the images

### ISSUE THREAD

**Issue by arasaac-dga** [asterics/AsTeRICS-Grid#308]
Related to closed issue #184 we continue having problems on some devices when we synchronise an account the first time. When the synchronization process has finished, we switch off internet conexion and go to some grids. As you can see in the video https://app.box.com/s/u99345semiv3hksssqs4dncw3uuvo74w many images are not shown (has not been cached). As an alternative solution we go to Manage Grids and press "Generate thumbnails" but as we commented in #184 is not a transparent solution for people due they don't know its double function. Offline use is something important due to the problems with internet connections in many countries or in schools. So, it would be neccesary to set a way to be sure that all the images are cached or create an option in configuration, for example, to be sure to make this process manually in case the system detects that not all the images have been cached. So, we consider that the system must control that all the images are really cached, advise in case of some error in synchronization process and offer an option to make it manually and be sure that all the images are finally cached.

**Comment by klues** [comment]
I've implemented this:
* all caching in the ServiceWorker is done with actual feedback for success
* as long as an image wasn't successfully cached, it will be retried after 15 seconds
* retries are also done after reloading / closing / restarting AsTeRICS Grid

I think this should fix all issues regarding caching. Please test at https://grid.asterics.eu/latest/
For testing purposes, I've left log messages which you can examine in the Javascript console. You can experiment with changing connection speed / set to offline / reloading AsTeRICS Grid while synchronization, see:

![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/88b52f32-7fb3-4b1c-8888-2b1a668be2e4)

**Comment by arasaac-dga** [comment]
We have been testing the improvement and it has somewhat improved the caching of images but not completely.  For us it still doesn't load all the images of all the boards when synchronising the first time (otherwise it opens one by one). Try following this procedure to reproduce the problem:

1) On the PC we reset a user (that we have synchronised also the mobile/tablet) 
2) On the mobile/Tablet we make sure that the user is reseted. 
3) We switch off the internet on the mobile/Tablet.
4) On the PC we load a different predefined communicator model on the user (we have used the new one from Hospitals in German). 
5) Once loaded and synchronised on the PC, activate the internet connection on the mobile/tablet and wait for it to synchronise (the roulette wheel stops spinning). 
6) When it finishes synchronising on the mobile/tablet, we disconnect Internet again.
7) When navigate to different grids, you can see that some images has not been loaded (some images are attached).

![AG_issue_cache](https://github.com/asterics/AsTeRICS-Grid/assets/82500056/fcbabb11-1f8e-4864-8d61-986994a6bc58)

If you connect the internet and open a grid of those that did not show any image and disconnect the internet again, now you can always see them even if it is offline. That is to say, it caches well but you have to browse the boards.

**Comment by klues** [comment]
Thanks for testing!
The problem was, that the animation shows that synchronization is complete, but in the background the image caching is still in progress. I've now changed it so that the animation also shows "syncing" during the image caching process.

Therefore there is now also an animation for offline users while image caching is in progress - the same without a cloud:
![grafik](https://github.com/asterics/AsTeRICS-Grid/assets/2537025/fc4cc7a4-a9c8-4c42-b973-f76be1444694)

Please test again at https://grid.asterics.eu/latest/

**Comment by arasaac-dga** [comment]
Yes. The synchronization animation was the key. You received the wrong feedback from the system. Now it is more accurate and in some tests that we made the result is better and seems to catch all. So, although we can continue testing it could be interesting to deploy in the main version as is now to improve the user's feedback.

**Comment by klues** [comment]
Great, then I'll release it to main version today. Please translate the new phrases in Spanish in crowdin before.

**Comment by arasaac-dga** [comment]
Made it. Thanks.

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2023-06-28-10.11%2F%2B0200
