### ISSUE TITLE
Grid Beta issue: Editing in Edge Windows

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#470]
So, I'm somehow unable to find the thread where we were talking about the new drag & drop options and the new grid overall, etc or maybe we did that only by email? Anyway, while testing I noticed an issue in the Edge browser in Windows tablet: (1) it doesn't react properly to touch and (2) the lines around the selected cell are not equal. I then also tried Firefox on Windows tablet and it was no issue there. Video here: https://we.tl/t-6kOl8aHfv6

**Comment by ms-mialingvo** [comment]
Oh, and I then tried also in the "normal" grid (not-beta) and it's no issue there either, Edge is working fine. So it's definitely a beta issue.

**Comment by klues** [comment]
> (1) it doesn't react properly to touch

It seems like it's interpreting your touch as little touch-move, which moves the element. Is Chrome / Firefox on Windows tablet working properly?

> (2) the lines around the selected cell are not equal

I've fixed this issue today, so maybe it was not the latest version. Maybe try to open grid.beta in a private tab in Edge?!

**Comment by ms-mialingvo** [comment]
> It seems like it's interpreting your touch as little touch-move, which moves the element. Is Chrome / Firefox on Windows tablet working properly?
Yes and AG in non-beta is working properly in Edge too.

> > (2) the lines around the selected cell are not equal
> 
> I've fixed this issue today, so maybe it was not the latest version. Maybe try to open grid.beta in a private tab in Edge?!

Mmmh, right now it's suddenly giving me a "the connection for this site is not secure, grid.beta.asterics-foundation.org  sent an invalid response. ERR_SSL_PROTOCL_ERROR" and not allowing me to access beta at all in Edge. Let me try to troubleshoot this on my end.

**Comment by ms-mialingvo** [comment]
Okay, I managed to access it, but the issue remains in the private tab. It looks like there's some connection, the elements where selecting works without problem are also the ones with a normal border, the ones where selecting is a issue are the ones that don't have an equal border.

**Comment by klues** [comment]
please try again at grid.beta in a private tab and open the console before, something like this:

![Image](https://github.com/user-attachments/assets/fa02f900-0ca1-4629-a0fc-334139385a50)

then you should see some messages like these while trying to select an element:

![Image](https://github.com/user-attachments/assets/a24dcbe7-384d-401a-97e3-38b7ecf666a5)

**Comment by ms-mialingvo** [comment]
Done. And I made additional videos for comparison (normal grid on Edge, gridbeta on Firefox) https://we.tl/t-JlCGylhXZ1

**Comment by klues** [comment]
OK, thanks, I think I've fixed it. I had some code preventing the selection while/after the element is dragged. I've now changed it and now the element is always selected after dragging, which I think is no problem and prevents this issue. The border issue should also be fixed.

**Comment by ms-mialingvo** [comment]
Yes, both works now :)

**Comment by klues** [comment]
Great!
