### ISSUE TITLE
Language levels - exclude nonmarked elements

### ISSUE THREAD

**Issue by ms-mialingvo** [asterics/AsTeRICS-Grid#639]
Currently, if I set up some elements as level 1 and some as level 2 and tell Asterics in the settings to show the grid up to level 1, it will not show the elements marked as level 2. It will however show all the elements that don't have any level applied to it.
Elements with no level applied should automatically be part of the vocabulary level "all" and invisible, instead.
I think for more clarity instead of having a level 10, level 10 should be "all", the "all" in brackets can be confusing.

**Comment by ms-mialingvo** [comment]
@klues testlink needed for beta-review

**Comment by klues** [comment]
Yes, I've added @BlagoCuljak to the contributors, so that he can push a branch directly to this project (where the workflow creating the link works).
@BlagoCuljak please post the link here afterwards - see [Collaboration guide](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_dev/collaboration.md) - always post a link to the testing release to the issue if you think it's ready for functional test.

**Comment by ms-mialingvo** [comment]
https://gridbeta-github.asterics-foundation.org/BlagoCuljak/512-babble-mode-for-vocabulary-level/pr (Here is where you should repost the link, @BlagoCuljak  :) )

I tested it and I'm realising this is a bit more complex than I thought. There are two issues still. (a) It's not working in the global grid. (b) when I put one category at a certain level to make it visible, then click on the category, it's not showing the elements of that category, even though I'd expect that. So I guess the rule should not be a sweeping hide-all-elements-with-no-level-marker but the rule should be a more complex if-one-element-in-a-specific-board-has-a-level-marker-hide-all-elements-with-no-level-marker yet if-no-element-in-a-specific-board-has-a-level-marker-show-all-elements.

https://github.com/user-attachments/assets/7a878de6-9ee9-4f6c-a9d7-64d05e67aaaf

**Comment by BlagoCuljak** [comment]
@ms-mialingvo I made push with corrections:
https://gridbeta-github.asterics-foundation.org/BlagoCuljak/639-language-levels-exclude-nonmarked-elements/pr

**Comment by ms-mialingvo** [comment]
I tested it and it's (a) is solved, yay! (b) is solved for normal grids, but not for global grids. The same logic (if-no-element-in-the-global-grid-has-a-level-marker-show-all-elements) should apply to global grids so it doesn't end up looking like:

<img width="1135" height="765" alt="Image" src="https://github.com/user-attachments/assets/78c303c6-f930-4e60-a199-0a58f373a39f" />

but like

<img width="1370" height="792" alt="Image" src="https://github.com/user-attachments/assets/b675568d-7383-4a18-aa8d-51966178d4ec" />

**Comment by BlagoCuljak** [comment]
@ms-mialingvo I don't really follow, and I am very much confused..

There are two issues still. **(a) It's not working in the global grid.** (b) when I put one category at a certain level to make it visible, then click on the category, it's not showing the elements of that category, even though I'd expect that. So I guess the rule should not be a sweeping hide-all-elements-with-no-level-marker but the rule should be a more complex if-one-element-in-a-specific-board-has-a-level-marker-hide-all-elements-with-no-level-marker yet if-no-element-in-a-specific-board-has-a-level-marker-show-all-elements.

And then:

I tested it and it's **(a) is solved**, yay! **(b)** is solved for normal grids, **but not for global grids.** The same logic (if-no-element-in-the-global-grid-has-a-level-marker-show-all-elements)

(a) Not working in global grid - > solved
(b) Doesn't work in global grid. 

What exactly is solved then?

**Comment by ms-mialingvo** [comment]
Read (b) again. What did you change for (b) for the normal grids?
Now that change should happen for the global grids too.

**Comment by BlagoCuljak** [comment]
@ms-mialingvo Do I need to display all items for connected grid if element we clicked is coming from global grid. Is that what you are saying?

**Comment by ms-mialingvo** [comment]
> (b) is solved for normal grids, but not for global grids. **The same logic (if-no-element-in-the-global-grid-has-a-level-marker-show-all-elements) should apply to global grids so it doesn't end up looking like:**

Replicate the first image, then the issue should be clear.

**Comment by BlagoCuljak** [comment]
@ms-mialingvo here it is: https://gridbeta-github.asterics-foundation.org/BlagoCuljak/639-language-levels-exclude-nonmarked-elements/pr

**Comment by ms-mialingvo** [comment]
@BlagoCuljak No. You just reverted (a) for the global grid.

(a) elements with no level applied should automatically be part of the vocabulary level "all" and invisible, however:

(b) if-one-element-in-a-specific-board-has-a-level-marker-hide-all-elements-with-no-level-marker yet if-no-element-in-a-specific-board-has-a-level-marker-show-all-elements

(a) and (b) should apply to normal grids and to the global grid.

**Comment by BlagoCuljak** [comment]
@ms-mialingvo I really don't understand these descriptions. Sorry. I have closed PR, I hope someone can continue the work, but I just can not understand these requirements.

**Comment by klues** [comment]
I think I understand it and I think I could do it. However:

> I think for more clarity instead of having a level 10, level 10 should be "all", the "all" in brackets can be confusing.

`(all)` is currently just: "always show all elements" - so in fact disable the progressive language feature.

It would be probably similar to `10 (all)` - which shows all elements with level `<= 10` - however would probably have some different result with the rule (a) - because with the logic applied also for level `10` elements with no level would be invisible, correct?!

So I think there probably should be just one choice `all` (without brackets) - as now at the start of the list? And level `10` as now - with the same logic applied as for all other levels?!

**Comment by ms-mialingvo** [comment]
It doesn't really matter to me if it's

Level 1-10 + all
or
Level 1-9 + all ( = formely level 10)

only that 10 "steps" is a nice round number ;) but whatever is easier to program.

**Comment by klues** [comment]
please test here: https://gridbeta-github.asterics-foundation.org/klues/639-klues-language-levels-nonmarked/pr

**Comment by ms-mialingvo** [comment]
Yes, nearly there, except that the collect element is disappearing if I use the level function for any element (in the global grid) since the collect element doesn't have an "level" setting. ...which I don't think is needed, though, it should always be visible-by-default. (Though if adding a "level" setting is faster to program, that would work for me too)

<img width="954" height="323" alt="Image" src="https://github.com/user-attachments/assets/784ab3b4-12cf-414a-92dc-e2b4a55b59c1" />

<img width="958" height="246" alt="Image" src="https://github.com/user-attachments/assets/6ea6965b-2176-49c1-abde-51b5c592f309" />

**Comment by klues** [comment]
ok, changed it so that all non-normal elements (collection bar, live elements, prediction elements) are shown always - all have no setting for language level. Test again in 2 minutes at the link above.

**Comment by ms-mialingvo** [comment]
Perfect 👍

**Comment by klues** [comment]
released with https://github.com/asterics/AsTeRICS-Grid/releases/tag/release-2025-10-24-14.10%2F%2B0200
